In [2]:
import numpy as np

In [5]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [7]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [8]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(20,10) # 1st argument is greater than 2nd argument, so it returns empty array.

array([], dtype=int64)

In [10]:
np.arange(-10,5)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4])

In [11]:
np.arange(10,30,5)

array([10, 15, 20, 25])

arange function accepts only 3 arguments, so it raises TypeError.

In [ ]:
np.arange(10,30,5,6) 

TypeError: Cannot interpret '6' as a data type

By default, the dtype of the array is float. So it returns an array of 3 zeros with float data type.

In [ ]:
np.zeros(3) 

array([0., 0., 0.])

If we change the system default data type then it becomes hyperparameter else it is just a parameter.

In [ ]:
np.zeros(3,dtype=int) 

array([0, 0, 0])

In [18]:
np.zeros([2,2],dtype=int) 

array([[0, 0],
       [0, 0]])

In [19]:
np.ones(2)

array([1., 1.])

In [23]:
np.ones([5,4],dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [24]:
np.twos(2)

AttributeError: module 'numpy' has no attribute 'twos'

In [25]:
rand(3,2)

NameError: name 'rand' is not defined

In [26]:
random.rand(3,2)

NameError: name 'random' is not defined

In [27]:
np.random.rand(3,2)

array([[0.23873788, 0.60358924],
       [0.50270284, 0.78608513],
       [0.05300728, 0.04136562]])

In [28]:
np.random.rand(3,2)

array([[0.60547751, 0.3140567 ],
       [0.52198953, 0.12501728],
       [0.50438109, 0.33066555]])

The np.random.randint() function in Python's NumPy library generates random integers sampled from a discrete uniform distribution over a specified half-open interval [low, high). This means the low value is inclusive, but the high value is exclusive.

In [29]:
np.random.randint(2)

0

In [31]:
np.random.randint(2)

1

In [32]:
np.random.randint(4)

2

In [33]:
np.random.randint(1,8)

2

In [ ]:
np.random.randint(1,8,4)

array([1, 6, 2, 3], dtype=int32)

In [35]:
np.random.randint(1,8,(2,3))

array([[5, 3, 4],
       [3, 5, 2]], dtype=int32)

In Python, reshape() function is used to give a new shape to an existing NumPy array without changing its data.

In [36]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
np.arange(1,13).reshape(3,5)

ValueError: cannot reshape array of size 12 into shape (3,5)

# Slicing

In [3]:
b = np.random.randint(10,20,(5,4))
b

array([[10, 19, 15, 15],
       [16, 19, 15, 13],
       [15, 13, 10, 16],
       [13, 14, 15, 15],
       [15, 18, 10, 19]], dtype=int32)

In [4]:
b[:]

array([[10, 19, 15, 15],
       [16, 19, 15, 13],
       [15, 13, 10, 16],
       [13, 14, 15, 15],
       [15, 18, 10, 19]], dtype=int32)

In [5]:
b[0]

array([10, 19, 15, 15], dtype=int32)

In [6]:
b[0:5]

array([[10, 19, 15, 15],
       [16, 19, 15, 13],
       [15, 13, 10, 16],
       [13, 14, 15, 15],
       [15, 18, 10, 19]], dtype=int32)

Reverses the order of the rows in the array.

In [ ]:
b[::-1] 

array([[15, 18, 10, 19],
       [13, 14, 15, 15],
       [15, 13, 10, 16],
       [16, 19, 15, 13],
       [10, 19, 15, 15]], dtype=int32)

Reverses the order of the rows in the array and selects every second row.

In [ ]:
b[::-2] 

array([[15, 18, 10, 19],
       [15, 13, 10, 16],
       [10, 19, 15, 15]], dtype=int32)

In [14]:
b.max()

np.int32(19)

In [15]:
b.min()

np.int32(10)

In [16]:
b.mean()

np.float64(14.75)

# Indexing

In [29]:
b[0,1]

np.int32(19)

In [30]:
b[-3,-3]

np.int32(13)

Select all rows, column 1

In [ ]:
b[:,1] 

array([19, 19, 13, 14, 18], dtype=int32)

In [21]:
b[0:5, 0:6]

array([[10, 19, 15, 15],
       [16, 19, 15, 13],
       [15, 13, 10, 16],
       [13, 14, 15, 15],
       [15, 18, 10, 19]], dtype=int32)

In [ ]:
b[2:3, :4] # 2nd row and all columns

array([[15, 13, 10, 16]], dtype=int32)

In [23]:
b[2:3,0:2] # 2nd row and 1st and 2nd columns

array([[15, 13]], dtype=int32)

In [ ]:
b[1:4,1:4] # 2nd, 3rd and 4th rows and 2nd, 3rd and 4th columns

array([[19, 15, 13],
       [13, 10, 16],
       [14, 15, 15]], dtype=int32)

# Masking

Masking in NumPy is a technique used to filter, extract, modify, or manipulate specific elements in an array based on a conditional boolean test.

In [26]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [28]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])